INSERT INTO TB_PESSOA(PES_ID, PES_TIPO, PES_SITUACAO, PES_NOME,PES_APELIDO, PES_DATA_NASCIMENTO) VALUES ( 1, 'FISICA', 'ATIVO', 'Administrador', 'adm', '2000-10-20');
INSERT INTO TB_PESSOA_FISICA(PES_ID,PF_RG, PF_CPF) VALUES ( 1, '00000000001', '000000001');


INSERT INTO TB_USUARIO(IP_ID, US_IS_ADMINISTRADOR, US_LOGIN, US_SENHA, PES_ID) VALUES ( 1, true, 'admin', '123', 1);
